[미션 0] x,y 좌표찍기 구현 완료했습니다.
sproutt/heroes-java-racing-game pull request #1
Opened 2020-02-11 15:18 UTC by imbf

남이 작성한 테스트 기반 코드를 보기만 했지 직접 작성한 것은 처음이었습니다.

메소드 이름 짓는 것과 클래스 이름 짓는 것도 생소했고 Junit을 사용하는 것도 생소 했습니다.

하지만 계속 생각하면서 재밌어 하는 제 자신을 보는 게 가장 즐거웠습니다 ㅎㅎㅎ

아 그리구 블로그 포스팅이나 도큐먼트들을 영어로 조금 봐두었던게 좀 도움이 된거 같습니다.

처음으로 받는 깃헙 코드리뷰네요 !!  아주 기대 됩니다

2020-02-11 15:34 UTC, hyukjin-lee commented
고생하셨습니다. 코드리뷰는 모두가 미션을 완수 했을 때 일괄적으로 하겠습니다.

2020-02-15 06:57 UTC, hyukjin-lee requested changes
고생하셨습니다.
전체적으로 코드 가독성도 좋고
정규표현식을 사용해서 많은 로직도 줄이셨네요.

피드백 몇 개 남겼으니 반영해주시고 commit push 하시면 되겠습니다.

2020-02-15 06:57 UTC, hyukjin-lee commented on src/main/java/Extractor.java
> +    public ArrayList<Integer> extractCoordinate(String expression) {
자바의 어머니 조슈아 블로크의 
effective java 에는 '객체는 인터페이스를 사용해 참조하라.'
라는 부분이 있습니다.
한번 읽어보시고 개선해보시면 좋을 것 같네요.

https://jaehun2841.github.io/2019/03/01/effective-java-item64/#%EC%9C%A0%EC%97%B0%ED%95%9C-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%A8%EC%9D%84-%EC%83%9D%EC%84%B1%ED%95%98%EB%8A%94-%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4-%ED%83%80%EC%9E%85-%EB%B3%80%EC%88%98

2020-02-15 06:57 UTC, hyukjin-lee commented on src/main/java/Extractor.java
> +        for (String element : expression.split("\\(|,|\\)")) {
정규표현식을 사용하실 줄은 몰랐네요. good 👍

2020-02-15 06:57 UTC, hyukjin-lee commented on src/main/java/Extractor.java
> +                numbers.add(Integer.valueOf(element));
보통 자바 영역은 google style guide 를 일반적인 코딩컨벤션(규칙)으로 생각하는데요,
if 문 과 for 문의 block 을 생략하지 않는게 컨벤션입니다.

https://google.github.io/styleguide/javaguide.html#s4.1-braces
https://kkangeva.tistory.com/39

2020-02-15 06:57 UTC, hyukjin-lee commented on src/main/java/Extractor.java
> +    }
number의 범위에 대한 규약이 있는데, production code 에서 그것을 필터링 하고 있지 않네요.

2020-02-15 06:57 UTC, hyukjin-lee commented on src/test/java/ExtractorTest.java
> +    public void testOneCoordinates(){
함수명에 한글도 쓸 수 있습니다. 테스트코드 가독성을 위해 한글 사용도 한번 고려해보시는 것도 좋을 것 같아요.
JUnit 5 버전에는 @DisplayName("테스트 뭐시기") 라는 어노테이션으로 테스트 케이스를 문자열로 적을 수 있습니다. (그냥 참고만)

2020-02-15 06:57 UTC, hyukjin-lee commented on src/test/java/ExtractorTest.java
> +        expression = "(8,10)";
8,10 경우만 세팅해주셨는데요,
각 테스트 케이스에서 값을 다르게 해야 될 텐데
이 값에 대해서만 확인하는게 정상적인 테스트인지 생각해보셔야 할 것 같습니다.
예를 들어 요구사항에 있는 25 이상의 값이나 음수에 대한 값을 넣어보는 테스트를 안하셨습니다.

2020-02-15 06:57 UTC, hyukjin-lee commented on src/test/java/ExtractorTest.java
> +        assertThat(extractor.extractCoordinate(expression).size()).isNotEqualTo(1);
사이즈를 체크하기 보다는 return 되는 값이 정확한지 isEqualTo()를 사용하여 테스트 할 수 있지 않을까요?

2020-02-15 06:57 UTC, hyukjin-lee commented on src/test/java/ExtractorTest.java
> +            assertThat(number).isBetween(1,24);
이 값을 초과하는 것에 대한 테스트가 없습니다.

2020-02-15 07:02 UTC, imbf commented
반영해서 작성 하겠습니다!!

2020-02-15 09:33 UTC, dadadamarine commented on src/test/java/ExtractorTest.java
> +        expression = "(8,10)";
내가 이 테스트를 왜하는지 목적을 먼저 생각해 보면 좋을것 같습니다.
- 제작하신 Extractor는 1~24값만 받아야한다
- 1~24값만 받도록 잘 구현이 되있는지 확인하기 위해서 -> 유효 하지 않는 값을 입력하는 경우를 테스트 함
- 테스트를 통과하면 조건에 맞게 잘 구현되어 있는것 이라는 보증을 할 수 있다.

이렇게 다른 구현사항에도 대입해 보면서 테스트의 역할에 대한 감을 가져가는것도 좋을 것 같네요.

2020-02-17 05:06 UTC, imbf commented on src/main/java/Extractor.java
> +    public ArrayList<Integer> extractCoordinate(String expression) {
아주 효율적인 사용법 인것 같아요!!

2020-02-17 05:15 UTC, imbf commented on src/test/java/ExtractorTest.java
> +        expression = "(8,10)";
그렇다면 다양한 데이터 값을 가진 테스트 데이터 셋을 구성하는 것도 좋은 테스트 보증서를 만들기 위한 하나의 방법이겠네요!!

2020-02-20 07:33 UTC, imbf commented
피드백 반영 완료 했습니다.
2번째 commit은 잘못 구현해서 다시 수정해서 3번째 commit 남겼습니다!!!

2020-02-20 07:46 UTC, esp2ar0 commented
피드백 반영 알맞게 잘 하셨네요~^^

2020-02-20 07:48 UTC, imbf commented
감사합니당 ㅎㅎㅎ 머지 해주시나용?

2020-03-11 07:54 UTC, merged