Step00
sproutt/heroes-java-racing-game pull request #10
Opened 2020-02-15 12:24 UTC by kanamycine

처음으로 컴퓨터를 공부하는 스터디에 들어와서,, 처음으로 접해보는 자바를 다루게 되어 정말 재밌었습니다... (but 개인적으로 느낀 난이도는 fire... )처음 접해보는 intelliJ 처음 접해보는 OOP,,, 아직은..모르는 것 투성이고, 발생하는 모든 에러나 문제를 마주할 때 마다 구글링을 해야 하지만 무언가에 이렇게 열중해 본 것도 오랜만인 것 같습니다...  초등학생이 짠 것 같은 코드겠지만, 보고 있으면 굉장히 뿌듯하네요 !!! 이런 기회를 맛보게 해주셔서 정말 감사드립니다.  앞으로도 최선을 다해 열심히 참여하도록 하겠습니다 ...!!  피드백이 굉장히 두렵지만 오늘 밤은 해냈다는 기분으로 하루를 마무리 하겠습니다 하하하 다들 감사합니다

2020-02-16 02:19 UTC, dadadamarine reviewed
코드가 읽기편하네요. 고생하셨습니다.

2020-02-16 02:19 UTC, dadadamarine commented on build.gradle
> +    implementation 'junit:junit:4.12'
왜 여러줄로 보일까요 ㅇ.ㅇ 
이건 그냥 보여서 적었습니다

2020-02-16 02:19 UTC, dadadamarine commented on src/main/java/Extractor.java
> +        String restr = str.replaceAll("[^0-9,]","");
변수는 **약어를 쓰지 않는**게 좋습니다. 

변수를 줄여서 얻는 이득이 전혀 없고, 반대로 읽는사람의 가독성이 떨어지는 단점이 크죠.
str도 str대신, 다른 사람이 딱 이 화면만 봤을때(배경지식 없이) str이 뭔지 이해 할 수 있는 변수명이 필요합니다.
타입이 String 인건 옆에 'String' 이라고 써져있어서 필요없는 정보이구요.
그거 말고 이게 어디서 들어오는 정보인지(commandLineInput), 어떤 형태로 들어오는지(numbersWith
Bracket) 등등으로 표현할 수 있을 것 같네요.

2020-02-16 02:19 UTC, dadadamarine commented on src/main/java/Extractor.java
> +
출처 표기 안하셔도 됩니다. 
이런데 1초도 시간 안쓰셔도 되여

2020-02-16 02:19 UTC, dadadamarine commented on src/main/java/Extractor.java
> +        y = digits[1];
코드를 잘짜셔서 객체에 대한 이야기를 조금 하고싶네요.

현재 객체의 이름은 Extractor이고, 이 객체에서 하는 역할중 하나가 Extract(String str) {
기능입니다.
숫자 추출기에서, 숫자 추출 동작을 하는거죠.

위 역할에서 x,y 변수로 값을 저장하는 행동은 불필요해 보입니다.
객체에 필요없는 코드는 최소한으로 줄이는게, 이 객체의 역할을 명확히 하는데 도움이 될 것 같습니다.

ps. 위 클래스에서 int[] digits;을 굳이 저장할 필요도 없는 것 같습니다.

2020-02-16 02:19 UTC, dadadamarine commented on src/main/java/Extractor.java
> +    int[] Extract(String str) {
자바 컨벤션을 지켜주세요.

객체명은 대문자로 시작
메서드 명은 소문자로 시작, camelCase로 작성

2020-02-16 02:19 UTC, dadadamarine commented on src/test/java/ExtractorTest.java
> +    }
굳이 이 객체를 생성할 필요가 있나? 에 대한 고민도 해보시면 좋을 것 같습니다.

2020-02-16 06:10 UTC, hyukjin-lee requested changes
고생하셨습니다.

리뷰 조금 남겼으니 확인 부탁드려요~

2020-02-16 06:10 UTC, hyukjin-lee commented on src/main/java/Extractor.java
> +    int y;
접근제어자를 모두 생략하신 이유가 있을까요?

2020-02-16 06:10 UTC, hyukjin-lee commented on src/test/java/ExtractorTest.java
> +        extract = null;
자바는 null 로 해준다고 객체의 메모리 해제가 되는 것이 아니라, 기존 객체는 메모리의 어딘가에 떠돌아다니다가 Garbage Collection 과정에서 사라지게 됩니다. (그냥 참고만..)

2020-02-16 06:10 UTC, hyukjin-lee commented on src/test/java/ExtractorTest.java
> +        assertArrayEquals(digits, extract.Extract("(8,9,10)"));
두 개 이상의 값이 들어가면 앞의 두개는 나오도록 짜보면 어떨까요?

2020-02-16 06:10 UTC, hyukjin-lee commented on src/test/java/ExtractorTest.java
> +        assertArrayEquals(digits, extract.Extract("(8,)"));
1개의 값이 들어가면 하나의 값이라도 나오도록 짜면 어떨까요? ex 8,0
그냥 추가 제안입니다. 다 0,0 으로 하면 너무 쉬운 것 같아서요 ㅎㅎ

2020-02-16 06:10 UTC, hyukjin-lee commented on src/test/java/ExtractorTest.java
> +}
정상적인 케이스에 대한 테스트가 없는 것 같습니다.
이 코드가 정상적인 케이스를 받았을 때 값이 내가 예상한대로 나오는지 검증하는 테스트도 필요할 것 같습니다.

2020-02-16 06:10 UTC, hyukjin-lee commented on src/main/java/Extractor.java
> +            int[] ErrorValue = {0,0};
자바의 코딩 컨벤션은 변수명이 소문자로 시작하는 명사라는 점입니다.
(메서드 명은 소문자로 시작하는 동사)
형식은 camelCase 를 사용합니다.

2020-02-17 12:12 UTC, kanamycine commented on build.gradle
> +    implementation 'junit:junit:4.12'
우선 리뷰해주셔서 감사합니다 !!!!!
"build.gradle" file은 제가 손댄적이 없어서 잘은 모르겠습니다...!!

2020-02-17 12:19 UTC, kanamycine commented on src/main/java/Extractor.java
> +    int y;
딱히 이유는 없었습니다 수정하겠습니다 !!!

2020-02-17 12:23 UTC, kanamycine commented on src/test/java/ExtractorTest.java
> +        assertArrayEquals(digits, extract.Extract("(8,9,10)"));
네 해보겠습니다 !!

2020-03-11 07:55 UTC, merged