[미션 0] 좌표 구하기 단위 테스트 구현 완료했습니다.
sproutt/heroes-java-racing-game pull request #2
Opened 2020-02-12 12:19 UTC by gxxrxn

미션 의도대로 잘 구현한건지 모르겠네유,,,,ㅠ,,, 몇번을 갈아엎었는지 모르겠습니닷,,,,ㅋㅋ
intellij도 처음 써보고, 이런 진행방식의 교육과정 자체가 처음이라 오류도 많이 났고 모르는 부분도 정말 많았지만, 정제된 질문을 하기 위해서 찾아보고 고민하는 시간을 진짜 많이 가졌던 것 같아요!!
그러다보니 문제들도 거의 해결돼서 굉장히 뿌듯했습니다. ㅎㅎ
미션하면서 밤을 꼬박 샐정도로 너무너무 재밌었습니다!! (맛보기라서 그런건가...?ㅋㅋ)
피드백 받으면 다음 미션은 더 자신있게 할 수 있을 것 같아서 무척 설레요ㅎㅎ

2020-02-15 07:22 UTC, hyukjin-lee requested changes
고생하셨습니다. 
클래스화 해서 코드를 짜려고 노력하신 점 좋네요.
아직 객체지향적으로 코드를 짜기는 어려우신 것 같은데
천천히 같이 공부하면서 익혀가시면 됩니다.

리뷰 조금 남겼는데 반영해주시면 감사하겠습니다

2020-02-15 07:22 UTC, hyukjin-lee commented on src/main/java/Point.java
> +public class Point {
클래스화 노력 👍

2020-02-15 07:22 UTC, hyukjin-lee commented on src/main/java/Point.java
> +    private ArrayList<Integer> pointNums = new ArrayList<>();
자바의 어머니 조슈아 블로크의
effective java 에는 '객체는 인터페이스를 사용해 참조하라.'
라는 부분이 있습니다.
한번 읽어보시고 개선해보시면 좋을 것 같네요.

jaehun2841.github.io/2019/03/01/effective-java-item64/#%EC%9C%A0%EC%97%B0%ED%95%9C-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%A8%EC%9D%84-%EC%83%9D%EC%84%B1%ED%95%98%EB%8A%94-%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4-%ED%83%80%EC%9E%85-%EB%B3%80%EC%88%98

2020-02-15 07:22 UTC, hyukjin-lee commented on src/main/java/Point.java
> +    public boolean checkOutOfRange(int x) {
public 으로 하신 이유가 있을까요?

2020-02-15 07:22 UTC, hyukjin-lee commented on src/main/java/Point.java
> +    private void extractPointNums() {
이 함수가 대표적으로 외부에 공개되어야하는 우리의 기능인 것 같은데, private 으로 구현되었습니다.
생성자의 목적은 객체의 초기화를 위함인데,
초기화를 넘어서 로직의 책임이 다 생성자에 구현된 것 같습니다.

생성자는 내부 필드 변수들을 초기화하는 역할만 하고,
이 메서드를 외부로 공개하도록 짜보면 어떨까요?
(힌트 : 메서드에 파라미터와 리턴 값이 존재하도록 바꾼다)

2020-02-15 07:22 UTC, hyukjin-lee commented on src/main/java/Point.java
> +        String[] tmp = point.replaceAll(" ", "")
이번 과정 컨벤션 : 변수는 축약형을 사용하지 않는다. 모두 풀어서 쓰고 무엇을 의미하는지 정확히 나타낼 수 있어야한다.

2020-02-15 07:22 UTC, hyukjin-lee commented on src/main/java/Point.java
> +        // arraylist에 유효한 x,y 값으로 다시 넣기
주석으로 코드를 설명하셨습니다.
우리는 굳이 메소드를 분리하여 가독성을 높일 필요가 없이
코드에 주석을 추가하기만 하면 되는데
왜 메소드를 잘게 분리해서 이해하기 쉽게 짜라고 할까요?

2020-02-15 07:22 UTC, hyukjin-lee commented on src/test/java/PointTest.java
> +            assertEquals(tmp, 0);
값이 1개만 들어와도 두개 모두 0으로 하신건가요?
값이 1개만 들어오면 하나만이라도 제대로 나오도록 변경해보시면 좋을 것 같습니다.

2020-02-15 07:22 UTC, hyukjin-lee commented on src/test/java/PointTest.java
> +        System.out.println("Value is one. " + point.getPoint());
assert 에 실패하면 왜 실패했는지 정확하게 뜹니다.
테스트에 이러한 system out 문구는 불필요하지 않을까요?

2020-02-15 07:22 UTC, hyukjin-lee commented on src/test/java/PointTest.java
> +        Point point = new Point("(8, 10, 11)");
3개 이상 들어온 경우에 대해서도 테스트 해주셨군요 👍

2020-02-15 07:22 UTC, hyukjin-lee commented on src/test/java/PointTest.java
> +        assertThat(point.getXY().size()).isLessThanOrEqualTo(2);
size 말고 값이 정확히 반환됐는지 테스트 하는게 정확할 것 같은데,
어떻게 해야할까요?

2020-02-15 09:51 UTC, dadadamarine commented on src/main/java/Point.java
> +        this.point = point;
다 좋네요.
메서드의 네임과, 실제 동작들이 잘 매칭되어있는 점, 예외 상황에 대한 꼼꼼한 예측등이 인상깊습니다.

+
현재 객체가 Point라는 이름인데
Point(String point) 생성자가, String을 넣으면 문자열 들을 여라 과정을 통해 값들을 분류하는 역할을 하네요.
역할을 보았을때 이 객체의 이름은 '분류하는 기계 or 추출하는 기계'가 좀더 어울릴 것 같아요. 👍 

"객체" 라는게 뭘 의미하는지, 감을 잡아가는 과정이 되면 좋겠네요

2020-02-15 20:14 UTC, gxxrxn commented
접근제한자에 대해 곰곰히 생각해보지 않고 코드를 짰던 것 같아요,,,핫,, 그리고 사실 x, y 값 중 한개만 들어왔을 때 split(',')를 써버리니까 x값이 들어온건지 y값이 들어온건지 구분이 안되더라구요,, 그래서 그냥 둘다 0으로 만들어버린거였는데ㅎㅎ,,,, 역시나 피드백이 오네욥ㅋㅋㅋㅋㅋ 다음부턴 꾀 안부리겠음다,,,ㅎㅎ,,, 지금까지는 원하는 결과가 나오는 것에만 집중해서인지, 이렇게 피드백을 반영해서 다시 코드를 짜는게 저에겐 정말 생소한 경험인 것 같아요!!ㅎㅎ 정말 재밌습니당!! 또 다른 피드백이 기다려져요><

2020-02-20 07:22 UTC, gxxrxn commented
피드백 반영 완료했습니다!

2020-03-11 07:54 UTC, merged