[미션 Step 0] 좌표구하기 구현 완료했습니다. 리뷰 부탁드립니다.
sproutt/heroes-java-racing-game pull request #4
Opened 2020-02-13 09:09 UTC by Dodant

자바를 오랜만에 다루게되어 살짝 어설픈 부분이 있었지만, 그래도 나름 재밌었습니다. 
여태 이클립스 써왔는데 인텔리제이 써보니까 확실히 세련됐다는 느낌을 받았습니다.
많은 에러들과 싸우다보니 아는 힘보다 알아내는 힘이 중요하다는 것도 느끼게 되는 것 같아요.
바른 입력을 걸러내기위해 정규표현식을 사용했는데 정말 편한 도구인것 같습니다.
저 스스로도 문자열 다루는 것을 좀 많이 연습해야 될 것 같습니다.
미션은 재밌었어요 ^^ 피드백받는 것도 기대되고 다음 미션들도 많은 기대가 됩니다.

2020-02-15 07:35 UTC, hyukjin-lee requested changes
정말 고생하셨습니다

리뷰 몇개 남겼으니 반영해주시면 되겠습니다.

2020-02-15 07:35 UTC, hyukjin-lee commented on src/main/java/point/PointTest.java
> +public class PointTest {
Test 코드를 production package 에 같이 작성해주셨네요.
테스트 코드는 프로그램을 실서버에 배포하기 전에 배제되어야합니다.
main/java 가 아닌 test/java 에 구현하면 어떨까요?

2020-02-15 07:35 UTC, hyukjin-lee commented on src/main/java/point/Point.java
> +    static boolean isValidInput(String txt){
static 을 사용하신 이유가 있을까요?

2020-02-15 07:35 UTC, hyukjin-lee commented on src/main/java/point/Point.java
> +    static Point extract(String txt){
접근 제한자를 package-private 으로 하셨는데 이유가 있을까요?

2020-02-15 07:35 UTC, hyukjin-lee commented on src/main/java/point/Point.java
> +        return txt.matches("^[(]([1-9]|[1-2][0-4])[,]([1-9]|[1-2][0-4])[)]$");
이번 과정 컨벤션 : 변수는 축약형을 사용하지 않는다. 모두 풀어서 쓰고 무엇을 의미하는지 정확히 나타낼 수 있어야한다.

2020-02-15 07:35 UTC, hyukjin-lee commented on src/main/java/point/Point.java
> +    static boolean isValidInput(String txt){
isVaildInput 은 외부로 공개 되어야 하는 메서드라기 보다 extract 메서드에서 추출된 private 메서드 같습니다.
접근 제한을 private 으로 낮추시고, 거기에 따른 테스트 코드도 수정하면 어떨까요?

2020-02-15 07:35 UTC, hyukjin-lee commented on src/main/java/point/Point.java
> +        Point point = new Point();
point 객체를 생성해주는 이유가 있을까요?

2020-02-15 07:35 UTC, hyukjin-lee commented on src/main/java/point/Point.java
> +    public static void main(String[] args){
main 함수는 쓰이지 않으니 지우셔도 될 것 같습니다

2020-02-15 07:35 UTC, hyukjin-lee commented on src/main/java/point/PointTest.java
> +        assertFalse(Point.isValidInput("(,1"));
서로 다른 케이스를 테스트 하는 경우에는, 
테스트 메서드를 분리하는게 좋습니다.
왜 그럴까요?

2020-02-15 07:35 UTC, hyukjin-lee commented on src/main/java/point/PointTest.java
> +        assertFalse(Point.isValidInput("(100,100)"));
assert 데이터 정말 많이 작성해주셨네요 👍

2020-02-15 07:35 UTC, hyukjin-lee commented on src/main/java/point/Point.java
> +        if (isValidInput(txt)){
메서드 네이밍을 잘 하셨네요 👍

2020-02-15 07:35 UTC, hyukjin-lee commented on src/main/java/point/Point.java
> +            return null;
null 보다는 exception 을 throw 하는게 어떨까요?

2020-02-15 07:38 UTC, hyukjin-lee commented on src/main/java/point/PointTest.java
> +        assertNull(Point.extract("12"));
정상적으로 나오는 경우에 대한 검증 테스트가 없습니다.

2020-02-15 10:15 UTC, dadadamarine commented on src/main/java/point/Point.java
> +        return txt.matches("^[(]([1-9]|[1-2][0-4])[,]([1-9]|[1-2][0-4])[)]$");
정규식을 좋아하지 않아요... 개인 취향인것 같은 이 의견을 좀더 논리적이게 포장해보자면..

> 이 정규식은 딱 'input 숫자들의 범위 확인' 의 역할만 하고있는 것 같습니다.
> input형식 체크(띄어쓰기 등)도 같이 해주는 것도 아니고, 단순 숫자 범위는 비교 연산이 더 빠를거라는 생각이 드네유 (성능)
> number >= 1 || number <= 24보다 읽기 힘듭니다. (가독성)

2020-02-20 07:55 UTC, Dodant commented
피드백 반영했습니다 !!

2020-02-20 08:23 UTC, esp2ar0 requested changes
추가적으로, 이전의 리뷰에서 접근 제한자에 대한 부분과 테스트 케이스에 대한 부분도 의견 바랍니다~

2020-02-20 08:23 UTC, esp2ar0 commented on src/main/java/point/Point.java
> +        return this.rawString.matches("^[(]([1-9]|[1-2][0-4])[,]([1-9]|[1-2][0-4])[)]$");
정규식에 대한 피드백이 반영되지 않았네요.
빠트리신거라면 추가로 반영해주시고,
다른 의견이 있다면 적극적으로 표현해주세요

덧붙여 궁금한 점 질문 드려요.
만약 (1,19)가 입력된다면 어떻게 될까요?

2020-02-20 08:23 UTC, esp2ar0 commented on src/main/java/point/Point.java
> +        String txt = this.rawString;
변수 축약형에 대한 리뷰도 마찬가지입니다.

2020-03-11 07:54 UTC, merged