[미션 0] 좌표구하기 단위테스트 구현 완료했습니다.
sproutt/heroes-java-racing-game pull request #6
Opened 2020-02-13 14:42 UTC by chchoco

뭔가  완전히 잘못된것같아서 깨닫고 고쳐서 다시 올립니다 여러번 고쳤네요ㅠㅠ 처음에 intellij 세팅하는데만 엄청 애먹었습니다ㅠㅠ  초기 환경설정할때 헤매고 버전때문에 안되다가 고치고 한글 안나와서 좀 고쳤는데 갑자기 intellij가 아예 안켜지더라구요 ㅋㅋ 이러다가 미션못하는거 아닌가 걱정했는데 그래도 다행이도 해결해서 완료했네요 !! 단위테스트를 처음해봐서 잘 짠건지 아직도 모르겠지만ㅠㅠ 굉장히 좋은기능이라는것을 느꼈습니다! 또 이렇게 깃헙으로 올리는것도 처음이고 코드리뷰도 처음이에요! 깃헙사용이 여전히 서툴고 어렵네요ㅠㅠ 다음미션도 기대됩니다ㅎㅎ

2020-02-15 08:00 UTC, hyukjin-lee requested changes
고생하셨습니다.

리뷰 몇개 남겼으니 반영해주시면 되겠습니다.

2020-02-15 08:00 UTC, hyukjin-lee commented on src/main/java/point/Point.java
> +    private String input;
input 을 멤버변수로 가질 필요가 있을까요?

2020-02-15 08:00 UTC, hyukjin-lee commented on src/main/java/point/Point.java
> +    private List<String> strListXY;
이번 과정 컨벤션 : 변수는 축약형을 사용하지 않는다. 모두 풀어서 쓰고 무엇을 의미하는지 정확히 나타낼 수 있어야한다.

strList 는 자료형과 타입을 그대로 적은 변수명입니다.
그럼 자료형과 타입이 바뀌면 변수명도 수정하는 공사를 해야겠죠?

대신 좀 더 이 프로그램에서 의미있고 이해하기 쉬운 변수명으로 변경하면 어떨까요?

2020-02-15 08:00 UTC, hyukjin-lee commented on src/main/java/point/Point.java
> +    private ArrayList<Integer> valueXY;  //좌표를 추출하는 결과값
effective java 에는 '객체는 인터페이스를 사용해 참조하라.'
라는 부분이 있습니다.
한번 읽어보시고 개선해보시면 좋을 것 같네요.

jaehun2841.github.io/2019/03/01/effective-java-item64/#%EC%9C%A0%EC%97%B0%ED%95%9C-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%A8%EC%9D%84-%EC%83%9D%EC%84%B1%ED%95%98%EB%8A%94-%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4-%ED%83%80%EC%9E%85-%EB%B3%80%EC%88%98

2020-02-15 08:00 UTC, hyukjin-lee commented on src/main/java/point/Point.java
> +    private ArrayList<Integer> valueXY;  //좌표를 추출하는 결과값
위에는 List 인터페이스를 사용하고 이 부분은 ArrayList 를 사용하신 이유가 있으실까요?

2020-02-15 08:00 UTC, hyukjin-lee commented on src/main/java/point/Point.java
> +    public void setting(String input){  //문자열에서 좌표값만 추출
메서드는 객체의 행위를 나타냅니다. setting 이라는 단어보다 행위를 표현하는 동사가 일반적입니다.

2020-02-15 08:00 UTC, hyukjin-lee commented on src/main/java/point/Point.java
> +        valueXY.add(0,0); valueXY.add(1,0); //초기값 0으로 세팅
자바 진영 컨벤션에서는 
여러 문장을 한 줄에 적지 않습니다.

2020-02-15 08:00 UTC, hyukjin-lee commented on src/main/java/point/Point.java
> +}
공백 하나하나도 각 언어별로 컨벤션이 있습니다. 
지금은 코드 포멧팅 컨벤션이 안지켜진 것 같아요.
intellij 에서 단축키 하나면 코드 포멧팅을 자동으로 해줍니다.

The formatting shortcuts in Intellij IDEA are :
For Windows : Ctrl + Alt + L.
For Ubuntu : Ctrl + Alt + Windows + L.
For Mac : ⌥ (Option) + ⌘ (Command) + L.

참고 바랍니다.

2020-02-15 08:00 UTC, hyukjin-lee commented on src/main/java/point/Point.java
> +    public void setting(String input){  //문자열에서 좌표값만 추출
setting 은 xyCoorinate 라는 메서드에서 추출된 private 메서드 인 것 같습니다.
외부로 공개되는 public 보다 private 으로 접근제한자를 수정하면 어떨까요?

2020-02-15 08:00 UTC, hyukjin-lee commented on src/main/java/point/Point.java
> +                if(value<=0||value>=25) value=-1; // 범위를 넘어가면 -1을 넣어줌
보통 자바 영역은 google style guide 를 일반적인 코딩컨벤션(규칙)으로 생각하는데요,
if 문 과 for 문의 block 을 생략하지 않는게 컨벤션입니다.

google.github.io/styleguide/javaguide.html#s4.1-braces
kkangeva.tistory.com/39

2020-02-15 08:00 UTC, hyukjin-lee commented on src/main/java/point/Point.java
> +    public ArrayList<Integer> xyCoordinate(String input){
행위를 나타내는 동사로 메서드명을 생각해보시면 어떨까요?

2020-02-15 08:00 UTC, hyukjin-lee commented on src/main/java/point/Point.java
> +        for (int i =0;i<strListXY.size()&&i<2;i++){   //길이 최대 2개
주석으로 코드를 설명하셨습니다.
우리는 굳이 메소드를 분리하여 가독성을 높일 필요가 없이
코드에 주석을 추가하기만 하면 되는데
왜 메소드를 잘게 분리해서 이해하기 쉽게 짜라고 할까요?

2020-02-15 10:29 UTC, dadadamarine commented on src/main/java/point/Point.java
> +    public ArrayList<Integer> xyCoordinate(String input){
메서드 명이 읽는사람에게 아무런 정보도 주지 않아서 아쉽습니다.
메서드 네임은 메서드가 어떤 동작을 하는지 잘 표현해 줘야 할 것 같습니다.

2020-02-15 10:33 UTC, dadadamarine commented on src/test/java/point/PointTest.java
> +        //맨 처음 2개의 값만 추출한다.
이 주석 그대로 테스트 명으로 사용하시면 될 것 같습니다 : )
주석들이 아래 코드가 어떤 역할을 하는지 아주 잘 설명해 주고있습니다.
하지만, 충분히 메서드 명으로 대체할 수 있어보이네요.

ps. 주석을 지양해야 하는 이유를 찾아보시면 좋을 것 같아요!

2020-02-16 03:24 UTC, chchoco commented
리뷰감사합니다^^ ㅎㅎ 반영해서 고쳐서 다시올리겠습니다!

2020-02-20 07:50 UTC, chchoco commented
피드백 반영 완료했습니다!

2020-03-11 07:54 UTC, merged