[미션 (0)] x, y 좌표 구하기 구현 완료했습니다. 리뷰 부탁드립니다.
sproutt/heroes-java-racing-game pull request #8
Opened 2020-02-14 11:24 UTC by soyoungee

처음 입력값을 받을 때 스캐너를 사용해야할 것 같아서 어떻게 테스트에 넣을지 고민을 많이 했는데 실패했습니다.. 그래도 테스트에 끼워맞춘 코드이긴 해도 테스트는 모두 성공해서 다행이라고 생각이 들었습니다! 2학년 이후로 오랜만에 자바를 하니까 추억이 새록새록 떠오르고 재밌었습니다 ㅎㅎ 비록 아직 해결못한 에러가 있지만 더 열심히 해서 미션도 더 일찍 끝내도록 노력하겠습니다.

2020-02-15 10:46 UTC, dadadamarine reviewed
테스트를 짜고, 그걸 어떻게든 통과하게 끼워맞춰서 제작하는게 TDD처럼 보이네요 전

2020-02-15 10:46 UTC, dadadamarine commented on src/test/java/mission0.java
> +        }
`xy[0].replaceAll("[^0-9]", "")`연산을 위에서 이미 해서, 굳이 여기서 다시 할 필요는 없을 것 같아요.
어떻게 더 짧게 가능할까요?

2020-02-15 10:46 UTC, dadadamarine commented on src/test/java/mission0.java
> +        if (x >= 1 && x <= 24 && y >= 1 && y <= 24) {
``` java
    if (xy[1].replaceAll("[^0-9]", "").equals("")) {
        y = 0;
    }
    else {
        y = Integer.parseInt(xy[1].replaceAll("[^0-9]", ""));
    }
```
이 문장 전체가 위에 한번 나왔던것 같은데, 어떻게 위에꺼를 재사용해서 코드를 줄일 수 있지 않을까요?

2020-02-15 10:46 UTC, dadadamarine commented on src/test/java/mission0Test.java
> +        m = null;
null처리를 따로 해주는 이유가 있을까요?

2020-02-16 06:17 UTC, hyukjin-lee requested changes
고생하셨습니다.

피드백 몇개 남겼으니 확인 부탁드려요~

2020-02-16 06:17 UTC, hyukjin-lee commented on src/test/java/mission0.java
> +public class mission0 {
자바의 코딩 컨벤션 (애옹님의 자료) 를 참고해주세요.
클래스는 대문자로 시작하고,
메서드는 소문자로 시작하는 동사,
변수는 소문자로 시작하는 명사,
패키지명은 소문자로 시작하는 단어입니다.
그리고 camelCase 를 사용합니다.

2020-02-16 06:17 UTC, hyukjin-lee commented on src/test/java/mission0.java
> +//    }
사용하지 않는 코드는 과감하게 지우고 PR 올려주시면 좋을 것 같습니다~

2020-02-16 06:17 UTC, hyukjin-lee commented on src/test/java/mission0.java
> +    public String readCoords(String str) {
과정에서 축약형 변수명을 사용하지 않는 것을 규칙으로 하겠습니다. 의미있는 변수명을 지어주세요

2020-02-16 06:17 UTC, hyukjin-lee commented on src/test/java/mission0.java
> +            return "fail";
fail 보다는 exception 을 발생시켜보고 그것을 테스트해보면 어떨까요?

2020-02-16 06:17 UTC, hyukjin-lee commented on src/test/java/mission0Test.java
> +    public void case2() {
테스트 케이스가 어떤 테스트를 의미하는지 메소드명에 드러나면 좋을 것 같아요.
메서드명을 한글로도 적을 수 있으니 '정상적인_입력을_받았을_경우_두개값이_출력된다'
정도로 수정해주면 어떨까요?
이렇게 하면 테스트 결과 창에 어떤게 초록불이 들어오고 어떤게 빨간불이 들어와서 무슨 케이스의 테스트가 깨졌는지 알아보기 쉬워집니다.

2020-02-18 11:01 UTC, soyoungee commented on src/test/java/mission0.java
> +            return "fail";
else문 안에서 try catch문을 사용하는 게 맞나요? 조건문이 있을 때 그 안에서 예외처리를 하는 건지 궁금합니다.

2020-02-18 11:50 UTC, esp2ar0 commented on src/test/java/mission0.java
> +            return "fail";
예외처리를 해주라는 말이 아니라 예외를 던지라는 말 아닐까요?

또한 예외 처리는 예외가 발생하는 곳에서 합니다. 조건문 안에서 쓰지 말란 법은 없지요.

2020-03-11 07:55 UTC, merged