[미션 0] 좌표구하기 단위테스트 구현 완료했습니다. 리뷰 부탁드립니다.
sproutt/heroes-java-racing-game pull request #9
Opened 2020-02-15 05:00 UTC by Ahntoday

x, y 하나만 적었을 때, 2개 이상 적었을 때, 유효범위 넘어갔을 때. 상황들을 다 생각하면서, if 문으로 코드를 짰습니다.  한글인식 mapping 오류도 자꾸 떴고, x, y 하나만 적었을 때 x를 안 썼는지 y를 안썼는지 구분하기 위해 제 생각대로 작성한 코드를 컴퓨터가 인식하지 못해서 많이 고민했습니다.... 그래도 결국 if ( num1 == null ) -> if (num1 == "") -> if(num1.isEmpty()) 이렇게 계속 수정을 거쳐 컴퓨터가 인식하니까 진짜 행복했습니다. 맛보기 문제였지만 자바를 다시 열심히 공부하며 코딩공부를 열심히 해야겠다는 생각이 들었습니다!!!!

2020-02-15 11:08 UTC, dadadamarine reviewed
고생하셨습니다. 👍

2020-02-15 11:08 UTC, dadadamarine commented on src/main/java/Point.java
> +    public static String result(String str) {
음.. 메서드의 이름은 이 **메서드가 어떤 역할**을 하는지 설명해 줘야합니다.

가장 훌륭한 메서드 이름은 
메서드 이름말고 아무것도 안봐도 되는, **코드 내용을 모두 설명**해주는 이름이라고 하더라구요.
그러려면 **메서드가 짧을수록** 달성 가능성이 높아질 것 같네요.

2020-02-15 11:08 UTC, dadadamarine commented on src/main/java/Point.java
> +    public static String result(String str) {
아래 내용을 기능별로 메서드를 여러개로 나눠서 작성해보면 좋을 것 같습니다.

2020-02-16 06:03 UTC, hyukjin-lee requested changes
고생하셨습니다.

리뷰 조금 남겼으니 확인해주시면 감사하겠습니다

2020-02-16 06:03 UTC, hyukjin-lee commented on src/main/java/Point.java
> +        ArrayList<String> list = new ArrayList<String>();
자바의 어머니 조슈아 블로크의
effective java 에는 '객체는 인터페이스를 사용해 참조하라.'
라는 부분이 있습니다.
한번 읽어보시고 개선해보시면 좋을 것 같네요.

jaehun2841.github.io/2019/03/01/effective-java-item64/#%EC%9C%A0%EC%97%B0%ED%95%9C-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%A8%EC%9D%84-%EC%83%9D%EC%84%B1%ED%95%98%EB%8A%94-%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4-%ED%83%80%EC%9E%85-%EB%B3%80%EC%88%98

2020-02-16 06:03 UTC, hyukjin-lee commented on src/main/java/Point.java
> +        String[] splitStr = restr.split(",");
이번 과정에서 변수 이름은 모두 줄여서 쓰지 않습니다.
Str 같은 자료형을 나타내는 것도 굳이 필요할까 고민해보시는 것도 좋을 것 같습니다

2020-02-16 06:03 UTC, hyukjin-lee commented on src/test/java/PointTest.java
> +        System.out.println(point);
test code 에 system out 은 필요하지 않을 것 같습니다.
테스트가 실패하면 assert 가 친절하게 알려줍니다 ㅎㅎ

2020-02-16 06:03 UTC, hyukjin-lee commented on src/test/java/PointTest.java
> +}
정상적으로 돌아가는 케이스도 필요할 것 같아요~
이 코드가 정상적인 케이스를 받았을 때 결과가 잘 나오는지도 테스트 하는게 좋지 않을까요?

2020-02-16 06:03 UTC, hyukjin-lee commented on src/main/java/Point.java
> +        ArrayList<String> list = new ArrayList<String>();
변수명이 어떤 list 를 뜻하나요? 의미있게 작명해주시면 좋을 것 같습니다.

2020-02-16 06:03 UTC, hyukjin-lee commented on src/main/java/Point.java
> +        return "(" + x + "," + y + ")";
코드가 전체적으로 이해하기 힘든 것 같습니다~
우선은 리팩토링의 첫 단계로 변수명 작명을 잘해서 가독성을 조금이라도 높여보는 작업을 해보시는 게 좋을 것 같습니다.
(로직적인 부분은 다른 분들의 코드를 한번 참고하시고 본인의 로직을 한번 점검해보는 시간을 갖는 것도 나쁘지 않을 것 같습니다)

2020-02-16 06:03 UTC, hyukjin-lee commented on src/test/java/PointTest.java
> +        assertEquals(point.result("(8,25)"),"(8,0)");
테스트 코드를 직관적으로 잘 짜셨네요 ㅎㅎ
result 라는 메서드 명이 좀 더 의미있는 단어였다면 더 한눈에 들어오는
훌륭한 테스트 코드 였을 것 같습니다.

2020-02-16 06:03 UTC, hyukjin-lee commented on src/main/java/Point.java
> +    private static int y;
static 인 이유가 있을까요?

2020-02-16 06:03 UTC, hyukjin-lee commented on src/main/java/Point.java
> +    public static String result(String str) {
메서드가 static 인 이유가 있을까요?

2020-03-11 07:55 UTC, merged